[build]
  command = "npm run build"
  publish = ".next"
  functions = "functions"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
